import Head from 'next/head';
import React, { useState } from 'react';
import { members } from '../mocks';
import MemberList from '../components/MemberList';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Members</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="mt-10 md:mt-16 lg:mt-20 text-red-300 lg:text-8xl md:text-6xl text-5xl text-center font-semibold px-16 py-16">
          Members
        </h1>
        <MemberList members={members} />
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
